name: flutter_lession_2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  flutter_svg: ^1.0.3
  dio: ^4.0.6
  google_fonts: ^2.3.1
  json_annotation: ^4.4.0
  build_runner: ^2.1.8
  json_serializable: ^6.0.6
  equatable: ^2.0.3
  flutter_gen: ^4.1.0
  infinite_scroll_pagination: 3.1.0
  get_it: ^7.2.0
  cached_network_image: ^3.0.0
  percent_indicator: ^4.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  flutter_gen_runner: ^4.1.0

  flutter_lints: ^1.0.0
flutter_gen:

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enable: true

  colors:
    inputs:
      - assets/colors/colors.xml
flutter:

  uses-material-design: true

  assets:
    - assets/images/
